language: python
python:
  - 3.7
install:
  - pip install -r requirements.txt
before_script:
  - python manage.py migrate
  - python manage.py collectstatic --noinput
script:
  - black --check .
  - flake8 .
  - coverage run --source='.' manage.py test
  - coverage report -m
  - python debugg.py
after_script:
  - coveralls
deploy:
  - provider: elasticbeanstalk
    access_key_id: $ACCESSKEYID
    secret_access_key: $SECRETACCESSKEY
    region: us-east-1
    app: NYC-Composts
    env: NYC-Composts-dev
    bucket_name: elasticbeanstalk-us-east-1-420156536504
    true:
      branch: develop
  - provider: elasticbeanstalk
    access_key_id: $ACCESSKEYID
    secret_access_key: $SECRETACCESSKEY
    region: us-east-1
    app: NYC-Composts
    env: NYC-Composts-prod
    bucket_name: elasticbeanstalk-us-east-1-420156536504
    true:
      branch: main
